name: Python safety check

on:
  schedule:
    - cron: '*/7 * * * *'

env:
  DEP_PATH: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out develop
        uses: actions/checkout@develop

      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@develop
